name: Rollback Deployment
on:
  workflow_dispatch:
jobs:
  rollback:
    runs-on: [self-hosted, linux, development, ubuntu-24]
    steps:
      - name: Find latest backup
        id: backup
        run: |
          LATEST_BACKUP=$(ls -t /var/www | grep static-site.backup | head -n 1)
          echo "backup=$LATEST_BACKUP" >> $GITHUB_OUTPUT
      
      - name: Restore backup
        run: |
          rm -rf /var/www/static-site/*
          cp -r /var/www/${{ steps.backup.outputs.backup }}/* /var/www/static-site/
          echo "Restored from backup: ${{ steps.backup.outputs.backup }}"